api_platform:
    title: 'Onde - API'
    description: 'Api créé dans le cadre de mon projet de fin de deuxième années de Bachelor.'
    version: '1.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            enabled: false
